categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":rocket: Features"
    label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":beetle: Fixes"
    label: "bug"
  - title: ":racehorse: Performance"
    label: "performance"
  - title: ":rotating_light: Testing"
    label: "tests"
  - title: ":construction_worker: Continuous Integration"
    label: "ci"
  - title: ":books: Documentation"
    label: "doc"
  - title: ":hammer: Refactoring"
    label: "refactoring"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"

exclude-labels:
  - 'release-pr'

autolabeler:
  - label: 'ci'
    files:
      - '.github/**/*.yml'
    branch:
      - '/^ci-.+/'
  - label: 'bug'
    branch:
      - '/^\d{1,7}-+(\S+[-])?fix(([-]\S+|-|$))/'
    title:
      - '/fix\s/i'
  - label: 'enhancement'
    branch:
      - '/feat-/i'
    title:
      - '/add\s/i'
  - label: 'dependencies'
    branch:
      - '/^deps-\S+/'
    title:
      - '/bump\s/i'
  - label: 'release-pr'
    branch:
      - '/^release-\S+/'

template: |
  ## What's Changed

  $CHANGES
