name: Reusable Select PyPI Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      url:
        required: true
        type: string

jobs:
  publish-package:
    name: Publish to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    permissions:
      id-token: write
    steps:
    - name: 📦 Publish to PyPI
      if: ${{ inputs.environment }} == 'PyPI'
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: 📦 Publish to Test PyPI
      if: ${{ inputs.environment }} == 'Test PyPI'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
